# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rcpp_dfirst <- function(source_node, from, to, verbose, only_nodes, path_stream) {
    .Call('_familyR_rcpp_dfirst', PACKAGE = 'familyR', source_node, from, to, verbose, only_nodes, path_stream)
}

rcpp_bfirst <- function(source_node, from, to, n_epochs, paths_stream, nodes_stream) {
    .Call('_familyR_rcpp_bfirst', PACKAGE = 'familyR', source_node, from, to, n_epochs, paths_stream, nodes_stream)
}

rcpp_bfirst2 <- function(source_node, from, to, n_epochs, paths_stream, nodes_stream) {
    .Call('_familyR_rcpp_bfirst2', PACKAGE = 'familyR', source_node, from, to, n_epochs, paths_stream, nodes_stream)
}

